#undef SYSCONFDIR
#undef PLUGINSDIR
#undef PERLSCRIPTDIR

#undef HAVE_GTK
#undef HAVE_IMLIB
#undef HAVE_GNOME
#undef HAVE_GNOME_PANEL

#undef GTK_HEBREW
#undef GTK_HEBREW_RC

#undef MEM_DEBUG
#undef HAVE_IPV6

#undef HAVE_POPT_H
#undef HAVE_SOCKS_H

#undef HAVE_NCURSES_USE_DEFAULT_COLORS
#undef HAVE_CURSES_IDCOK

#undef HAS_CURSES
#undef USE_SUNOS_CURSES
#undef USE_BSD_CURSES
#undef USE_SYSV_CURSES
#undef USE_NCURSES
#undef NO_COLOR_CURSES
#undef SCO_FLAVOR
#undef NCURSES_970530
