#undef HAVE_GTK
#undef HAVE_GNOME
#undef HAVE_GNOME_PANEL
#undef SYSCONFDIR
#undef PLUGINSDIR
#undef PERLSCRIPTDIR
#undef GTK_10
#undef HAVE_SOCKS_H
#undef HAVE_IMLIB
#undef MEM_DEBUG
#undef HAVE_IPV6
#undef GTK_HEBREW
#undef GTK_HEBREW_RC

#undef HAVE_NCURSES_USE_DEFAULT_COLORS
#undef HAVE_CURSES_IDCOK

#undef HAS_CURSES
#undef USE_SUNOS_CURSES
#undef USE_BSD_CURSES
#undef USE_SYSV_CURSES
#undef USE_NCURSES
#undef NO_COLOR_CURSES
#undef SCO_FLAVOR
#undef NCURSES_970530
