static PERL_SIGNAL_ARGS_REC perl_signal_args[] =
{
    { -1, "gui channel open", { "CHANNEL_REC", NULL } },
    { -1, "send command", { "string", "SERVER_REC", "CHANNEL_REC", NULL } },
    { -1, "send command", { "string", "SERVER_REC", NULL } },
    { -1, "command ", { "string", "SERVER_REC", "CHANNEL_REC", NULL } },
    { -1, "default command", { "string", "SERVER_REC", "CHANNEL_REC", NULL } },
    { -1, "server event", { "string", "SERVER_REC", "string", "string", NULL } },
    { -1, "event ", { "string", "SERVER_REC", "string", "string", NULL } },
    { -1, "default event", { "string", "SERVER_REC", "string", "string", NULL } },
    { -1, "server incoming", { "SERVER_REC", "string", NULL } },
    { -1, "redir ", { "string", "SERVER_REC", "string", "string", NULL } },
    { -1, "ban new", { "BAN_REC", NULL } },
    { -1, "ban remove", { "BAN_REC", NULL } },
    { -1, "ban exception new", { "BAN_REC", NULL } },
    { -1, "ban exception remove", { "BAN_REC", NULL } },
    { -1, "ban type changed", { "string", NULL } },
    { -1, "commandlist new", { "COMMAND_REC", NULL } },
    { -1, "commandlist remove", { "COMMAND_REC", NULL } },
    { -1, "channel created", { "CHANNEL_REC", NULL } },
    { -1, "channel destroyed", { "CHANNEL_REC", NULL } },
    { -1, "channel name changed", { "CHANNEL_REC", NULL } },
    { -1, "channel topic changed", { "CHANNEL_REC", NULL } },
    { -1, "channel server changed", { "CHANNEL_REC", "Irssi::Server", NULL } },
    { -1, "channel query", { "CHANNEL_REC", NULL } },
    { -1, "channel wholist", { "CHANNEL_REC", NULL } },
    { -1, "channel sync", { "CHANNEL_REC", NULL } },
    { -1, "ctcp msg ", { "string", "SERVER_REC", "string", "string", "string", NULL } },
    { -1, "default ctcp msg", { "string", "SERVER_REC", "string", "string", "string", NULL } },
    { -1, "ctcp reply ", { "string", "SERVER_REC", "string", "string", "string", NULL } },
    { -1, "default ctcp reply", { "string", "SERVER_REC", "string", "string", "string", NULL } },
    { -1, "server lag", { "SERVER_REC", NULL } },
    { -1, "server lag disconnect", { "SERVER_REC", NULL } },
    { -1, "lag", { "string", "int", NULL } },
    { -1, "invitelist new", { "CHANNEL_REC", "string", NULL } },
    { -1, "invitelist remove", { "CHANNEL_REC", "string", NULL } },
    { -1, "channel mode changed", { "CHANNEL_REC", NULL } },
    { -1, "user mode changed", { "SERVER_REC", NULL } },
    { -1, "nick mode changed", { "CHANNEL_REC", "NICK_REC", NULL } },
    { -1, "netsplit add", { "NETSPLIT_REC", NULL } },
    { -1, "netsplit remove", { "NETSPLIT_REC", NULL } },
    { -1, "nicklist new", { "CHANNEL_REC", "NICK_REC", NULL } },
    { -1, "nicklist remove", { "CHANNEL_REC", "NICK_REC", NULL } },
    { -1, "nicklist changed", { "CHANNEL_REC", "NICK_REC", "string", NULL } },
    { -1, "nick gone changed", { "CHANNEL_REC", "NICK_REC", NULL } },
    { -1, "nick ircop changed", { "CHANNEL_REC", "NICK_REC", NULL } },
    { -1, "server nick changed", { "SERVER_REC", NULL } },
    { -1, "massjoin", { "CHANNEL_REC", "gslist_NICK_REC", NULL } },
    { -1, "rawlog", { "SERVER_REC", "string", NULL } },
    { -1, "server connect failed", { "SERVER_REC", NULL } },
    { -1, "server connected", { "SERVER_REC", NULL } },
    { -1, "server connecting", { "SERVER_REC", "ulongptr", NULL } },
    { -1, "server looking", { "SERVER_REC", NULL } },
    { -1, "server disconnected", { "SERVER_REC", NULL } },
    { -1, "event connected", { "SERVER_REC", NULL } },
    { -1, "server reconnect new", { "RECONNECT_REC", NULL } },
    { -1, "server reconnect remove", { "RECONNECT_REC", NULL } },
    { -1, "server reconnect not found", { "string", NULL } },
    { -1, "print text stripped", { "SERVER_REC", "string", "int", "string", NULL } },
    { -1, "dcc ctcp ", { "string", "DCC_REC", NULL } },
    { -1, "default dcc ctcp", { "string", "DCC_REC", NULL } },
    { -1, "dcc unknown ctcp", { "string", "string", "string", NULL } },
    { -1, "dcc reply ", { "string", "DCC_REC", NULL } },
    { -1, "default dcc reply", { "string", "DCC_REC", NULL } },
    { -1, "dcc unknown reply", { "string", "string", "string", NULL } },
    { -1, "dcc chat message", { "DCC_REC", "string", NULL } },
    { -1, "dcc created", { "DCC_REC", NULL } },
    { -1, "dcc destroyed", { "DCC_REC", NULL } },
    { -1, "dcc connected", { "DCC_REC", NULL } },
    { -1, "dcc rejecting", { "DCC_REC", NULL } },
    { -1, "dcc closed", { "DCC_REC", NULL } },
    { -1, "dcc chat message", { "DCC_REC", "string", NULL } },
    { -1, "dcc transfer update", { "DCC_REC", NULL } },
    { -1, "dcc request", { "DCC_REC", NULL } },
    { -1, "dcc get receive", { "DCC_REC", NULL } },
    { -1, "dcc error connect", { "DCC_REC", NULL } },
    { -1, "dcc error file create", { "DCC_REC", "string", NULL } },
    { -1, "dcc error file not found", { "string", "string", NULL } },
    { -1, "dcc error get not found", { "string", NULL } },
    { -1, "dcc error send exists", { "string", "string", NULL } },
    { -1, "dcc error unknown type", { "string", NULL } },
    { -1, "dcc error close not found", { "string", "string", "string", NULL } },
    { -1, "flood", { "SERVER_REC", "string", "string", "string", "string", NULL } },
    { -1, "autoignore new", { "SERVER_REC", "AUTOIGNORE_REC", NULL } },
    { -1, "autoignore remove", { "SERVER_REC", "AUTOIGNORE_REC", NULL } },
    { -1, "log new", { "LOG_REC", NULL } },
    { -1, "log remove", { "LOG_REC", NULL } },
    { -1, "log locked", { "LOG_REC", NULL } },
    { -1, "log started", { "LOG_REC", NULL } },
    { -1, "log stopped", { "LOG_REC", NULL } },
    { -1, "log written", { "LOG_REC", "string", NULL } },
    { -1, "notifylist new", { "NOTIFYLIST_REC", NULL } },
    { -1, "notifylist remove", { "NOTIFYLIST_REC", NULL } },
    { -1, "notifylist joined", { "SERVER_REC", "string", "string", "string", "string", "string", NULL } },
    { -1, "notifylist away changed", { "SERVER_REC", "string", "string", "string", "string", "string", NULL } },
    { -1, "notifylist unidle", { "SERVER_REC", "string", "string", "string", "string", "string", NULL } },
    { -1, "notifylist left", { "SERVER_REC", "string", "string", "string", "string", "string", NULL } },
    { -1, "plugin created", { "PLUGIN_REC", NULL } },
    { -1, "plugin loaded", { "PLUGIN_REC", NULL } },
    { -1, "plugin destroyed", { "PLUGIN_REC", NULL } },
    { -1, "plugin error already loaded", { "string", NULL } },
    { -1, "plugin error invalid", { "string", NULL } },
    { -1, "plugin error load", { "string", "string", NULL } },
    { -1, "plugin error not loaded", { "string", NULL } },
    { -1, "plugin error version", { "string", NULL } },

    { -1, NULL }
};
