.TH Irssi 1 "September 2002" "Irssi IRC client"
.SH NAME
Irssi \- a modular IRC client for UNIX
.SH SYNOPSIS
.B irssi
[-dv!?] [-c server] [-p port] [-n nickname] [-w password] [-h hostname]
.SH DESCRIPTION
.B Irssi
is a modular Internet Relay Chat client. It is highly extensible and
very secure. Being a fullscreen, termcap based client with many
features,
.B Irssi
is easily extensible through scripts and modules.
.SH OPTIONS
.TP
.BI "\-\-config="FILE
use 
.I FILE
instead of ~/.irssi/config.
.TP
.BI "\-\-home="PATH
.I PATH 
specifies the home directory of Irssi.
Default is 
.BR ~/.irssi
.TP
.BI "\-c, \-\-connect="SERVER
connects to 
.I SERVER
.TP
.BI "\-w, \-\-password="PASSWORD
use
.I PASSWORD 
for authentication.
.TP
.BI "\-p, \-\-port="PORT
automatically connect to 
.I PORT 
on server.
.TP
.BI "\-!, \-\-noconnect"
disables autoconnecting.
.TP
.BI "\-n, \-\-nick="NICKNAME
specify 
.I NICKNAME 
as your nick.
.TP
.BI "\-h, \-\-hostname="HOSTNAME
use
.I HOSTNAME
for your irc session.
.TP
.BI "\-d, \-\-dummy"
use dummy terminal mode.
.TP
.BI "\-v, \-\-version"
display the version of Irssi.
.TP
.BI "\-?, \-\-help"
show a help message.
.TP
.BI "\-\-usage"
display brief usage message.
.SH SEE ALSO
.B Irssi
has been supplied with a huge amount of documentation. Check /help or look
at the files contained by /usr/share/doc/irssi*
.SH FILES
.TP
.I /etc/irssi.conf
Global configuration file
.TP
.I ~/.irssi/config
Personal configuration file
.TP
.I ~/.irssi/config.autosave
Automatic save of the personal config file when it was changed externally
.TP
.I ~/.irssi/default.theme
Default irssi theme
.TP
.I ~/.irssi/away.log
Logged messages in away status
.TP
.I /usr/share/irssi/help/
Directory including many help files
.TP
.I /usr/share/irssi/scripts/
Global scripts directory
.TP
.I /usr/share/irssi/themes/
Global themes directory
.TP
.I ~/.irssi/scripts/
Default scripts directory
.TP
.I ~/.irssi/scripts/autorun/
Directory containing links to scripts that should be loaded
automatically on startup
.TP
.I ~/.irssi/startup
File containing a list of commands to execute on startup
.SH AUTHORS/CREDITS
.B Irssi
was written by Timo Sirainen
.B <cras@irssi.org>
.sp
This manpage was written by Istvan Sebestyen
.BR <stevee@alphanet.ch>
and Stefan Tomanek
.BR <stefan@pico.ruhr.de>
